@startuml

actor Client
entity Configuration
participant Histogramator
participant ChunkAggregator
database Store
queue Queue
queue SourceFlow

group setup histogram parameters
    Client -> Configuration: setup histogram's borders
    Configuration --> Histogramator: setup histogram parameters \n for chunks generation
    Configuration --> ChunkAggregator: setup histogram parameters for chunks generation
end

group chunk aggregation
    ChunkAggregator <-- SourceFlow: collect data
    ChunkAggregator --> ChunkAggregator: aggregate chunks
    ChunkAggregator <-> Store: store chunk and get id
    ChunkAggregator --> Queue: send ChunkId
end

group histogram accumulation
    Histogramator <-- Queue: receive ChunkId
    Histogramator -> Store: request chunk by id
    Histogramator <- Store: response chunk
    Histogramator --> Histogramator: accumulate chunks \n to histogram
    Histogramator -> Client: show histogram
end

@enduml